### ISSUE TITLE
Builtin: 12 unknown in Python output

### ISSUE THREAD

**Issue by danlupei** [opencog/moses#47]
Using MOSES on certain data with Python output gave me programs with the aforementioned error in them.
Comparing those programs with their rough Combo equivalents, it seems to me that "greater-than-zero" operator is not implemented for Python. Inspecting `iostream_combo.cc` further supports that claim, as there are only a handful of ops supported for Python and `<0` is indeed not one of them.

I wonder how complex would it be to add it - is that a matter of simply modifying `ostream_builtin` or are more reaching changes needed?

As a side note, I also noticed you use Python operators like `and` directly, infix-wise. If Python's `operator` module was used, you could invoke them prefix-wise. Maybe it would make it easier to generate Python programs from Combo.

**Comment by linas** [comment]
It should not be hard to fix this; I encourage you to do so and submit a patch.

Most (all?) of us are using various collections of scripts that can work with/parse the combo output directly, and do things with it. Its probably just as hard to create a python script that parses combo and does things with it, as it would be to fix the `iostream` to support correct python output.

There is one advantage to using combo natively: you can treat it as "data": i.e. store it in files, make copies, average them together (analogous to a "decision forest" -- individual combo programs are roughly comparable to individual decision trees in accuracy, performance).  You loose this ability to treat moses output as "data" when you use the python output.  (Mostly because python itself doesn't like to be treated as if it was "data"; it was really designed to be "code")
